pipeline {
    agent any

    environment {
        AWS_PROFILE = 'glimpses'
    }

    stages {
        stage('Build') {
            steps {
                dir('Backend/download') {
                    sh '''
                        set -e
                        rm -rf build build.zip
                        mkdir -p build
                        python3 -m pip install -r requirements.txt \
                          --target build \
                          --platform manylinux2014_x86_64 \
                          --implementation cp \
                          --python-version 3.13 \
                          --only-binary=:all: \
                          --upgrade
                        cp -r src/. build/
                        cd build && zip -r ../build.zip . && cd ..
                    '''
                }
            }
        }
        stage('Push to deployment-artifacts') {
            steps {
                dir('Backend/download') {
                    sh 'aws s3 cp build.zip s3://glimpses-deploy-artifacts-712906641804/download/build.zip'
                }
            }
        }
        stage('Terraform Init') {
            steps {
                dir('Infrastructure') {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Validate') {
            steps {
                dir('Infrastructure') {
                    sh 'terraform validate'
                }
            }
        }
        stage('Terraform Apply - download') {
            steps {
                dir('Infrastructure') {
                    sh 'terraform apply -target=module.download -auto-approve'
                }
            }
        }
        stage('Update Lambda code') {
            steps {
                sh 'aws lambda update-function-code --function-name glimpses-download --s3-bucket glimpses-deploy-artifacts-712906641804 --s3-key download/build.zip'
            }
        }
    }
}
