def repoUrl = 'https://github.com/HridayBuilds/Serverless-Image-Retrieval.git'
def branch = '*/main'

def jenkinsfiles = readFileFromWorkspace('jenkinsfiles.txt').readLines().findAll { it.trim() }

jenkinsfiles.each { path ->
    def jobName = path.split('/')[-3]

    pipelineJob(jobName) {
        description("Auto-generated by glimpses-seed from ${path}")
        configure { project ->
            def definitionXml = """
<definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps">
  <scm class="hudson.plugins.git.GitSCM" plugin="git">
    <configVersion>2</configVersion>
    <userRemoteConfigs>
      <hudson.plugins.git.UserRemoteConfig>
        <url>${repoUrl}</url>
      </hudson.plugins.git.UserRemoteConfig>
    </userRemoteConfigs>
    <branches>
      <hudson.plugins.git.BranchSpec>
        <name>${branch}</name>
      </hudson.plugins.git.BranchSpec>
    </branches>
    <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
    <submoduleCfg class="empty-list"/>
    <extensions/>
  </scm>
  <scriptPath>${path}</scriptPath>
  <lightweight>true</lightweight>
</definition>
"""
            def newDefinition = new XmlParser().parseText(definitionXml)
            def existingDefinition = project / definition
            existingDefinition.replaceNode(newDefinition)
        }
    }
}