pipeline {
    agent any

    environment {
        AWS_PROFILE = 'glimpses'
    }

    stages {
        stage('Terraform Init') {
            steps {
                dir('Infrastructure') {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Validate') {
            steps {
                dir('Infrastructure') {
                    sh 'terraform validate'
                }
            }
        }
        stage('Terraform Apply - buckets') {
            steps {
                dir('Infrastructure') {
                    sh 'terraform apply -target=module.buckets -auto-approve'
                }
            }
        }
    }
}
